### ISSUE TITLE
Explore & Profile Page

### ISSUE THREAD

**Issue by alistairholmes** [flutterdevzim/coursehub#1]
![Developers Page](https://user-images.githubusercontent.com/22801227/89104099-02879e00-d417-11ea-9301-32735e66c4d1.png)

**Comment by ignertic** [comment]
@alistairholmes confirm there will be another branch with the navigation implementation, probably will have to be the first branch to  be merged to master as to avoid conflicts when mergin

**Comment by alistairholmes** [comment]
@ignertic Thanks for the heads up, I overlooked that. Will see what I can do about merging the navigation in first.

**Comment by alistairholmes** [comment]
@ignertic #9

**Comment by ignertic** [comment]
![Screenshot_20200804-050625](https://user-images.githubusercontent.com/20477009/89248894-1d256700-d611-11ea-81c5-03ae14acc79f.jpg)
![Screenshot_20200804-050227](https://user-images.githubusercontent.com/20477009/89248898-1eef2a80-d611-11ea-9954-3657caf47b31.jpg)


@alistairholmes , which appBar would be preferable, given that the one with an image background will also be a PageView showcasing new courses or other relevant slides such as recent courses taken or courses enrolled in (showing progress).

**Comment by cybertanya** [comment]
Prefer the one with an image background

**Comment by alistairholmes** [comment]
Safe to close this @ignertic ?
